"""Captures router — packet capture CRUD, summary, AI analysis, packs."""

import asyncio
import logging
from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from ..models.analysis_packs import PackConfig, list_packs
from ..models.capture import (
    AnalysisRequest,
    AnalysisResultV2,
    CaptureInfo,
    CaptureSummary,
    StartCaptureRequest,
)
from ..services import ai_analyzer, capture, capture_retention

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/captures", tags=["captures"])


# ── Pack definitions ─────────────────────────────────────────────────────────

@router.get("/packs", response_model=List[PackConfig])
async def get_packs():
    """List all available analysis packs."""
    return list_packs()


# ── Capture CRUD ─────────────────────────────────────────────────────────────

@router.post("", response_model=CaptureInfo, status_code=201)
async def start_capture(req: StartCaptureRequest):
    """Start a new packet capture. Auto-links to active session."""
    try:
        info = await capture.start_capture(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

    from ..services import session_manager
    from ..models.session import ArtifactType
    await session_manager.auto_add_artifact(
        ArtifactType.CAPTURE,
        name=f"Capture: {info.name}",
        file_path=info.pcap_path,
        tags=["capture", "pcap", info.pack],
        metadata={"capture_id": info.id, "interface": info.interface, "bpf": info.bpf_expression, "pack": info.pack},
    )

    return info


@router.get("", response_model=List[CaptureInfo])
async def list_captures():
    """List all captures."""
    return await capture.list_captures()


@router.get("/status")
async def capture_status():
    """Get capture system status — storage usage, active captures."""
    storage = await capture_retention.get_storage_usage()
    captures = await capture.list_captures()
    active = [c for c in captures if c.status == "running"]

    return {
        "active_captures": len(active),
        "max_concurrent": 2,
        "storage": storage,
    }


@router.get("/{capture_id}", response_model=CaptureInfo)
async def get_capture(capture_id: str):
    """Get capture metadata."""
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")
    return info


@router.post("/{capture_id}/stop", response_model=CaptureInfo)
async def stop_capture(capture_id: str):
    """Stop a running capture."""
    try:
        return await capture.stop_capture(capture_id)
    except ValueError as e:
        raise HTTPException(404, str(e))


@router.delete("/{capture_id}")
async def delete_capture(capture_id: str):
    """Delete a capture and its files."""
    try:
        await capture.delete_capture(capture_id)
        return {"status": "ok", "capture_id": capture_id}
    except ValueError as e:
        raise HTTPException(404, str(e))


@router.get("/{capture_id}/download")
async def download_capture(capture_id: str):
    """Download the pcap file."""
    pcap = capture.get_pcap_path(capture_id)
    if not pcap:
        raise HTTPException(404, "Pcap file not found")
    return FileResponse(
        pcap,
        media_type="application/vnd.tcpdump.pcap",
        filename=f"{capture_id}.pcap",
    )


# ── Summary ──────────────────────────────────────────────────────────────────

@router.get("/{capture_id}/summary")
async def get_summary(capture_id: str):
    """Get the CaptureSummary for a completed capture.

    Returns structured statistics generated by the post-processing pipeline.
    This is the same data used as input to AI analysis.
    """
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")

    summary = capture.get_summary(capture_id)
    if not summary:
        raise HTTPException(404, "Summary not yet available. Capture may still be processing.")

    return summary


# ── AI Analysis ──────────────────────────────────────────────────────────────

async def _run_analysis_background(capture_id: str, req: AnalysisRequest) -> None:
    """Run AI analysis as a background task so the user can navigate away.

    Updates capture metadata with analysis_status for frontend polling.
    """
    info = capture.get_capture(capture_id)
    if not info:
        return

    try:
        # Mark as running
        info.analysis_status = "running"
        capture._captures[capture_id] = info
        capture._save_metadata(info)

        result = await ai_analyzer.analyze_capture(capture_id, req)

        # Record in session
        from ..services import session_manager
        from ..models.session import ArtifactType
        await session_manager.auto_add_artifact(
            ArtifactType.ANALYSIS,
            name=f"AI Analysis: {capture_id}",
            data={
                "summary": result.summary,
                "finding_count": len(result.findings),
                "health_badge": result.health_badge.value,
                "provider": result.provider,
            },
            tags=["analysis", "ai", result.provider, info.pack],
            metadata={"capture_id": capture_id},
        )

        # Mark done
        info = capture.get_capture(capture_id) or info
        info.analysis_status = "done"
        info.has_analysis = True
        info.analysis_error = None
        capture._captures[capture_id] = info
        capture._save_metadata(info)

        logger.info("Background analysis complete for capture %s", capture_id)

    except Exception as e:
        err_name = type(e).__name__
        err_detail = str(e) or "(no detail)"
        logger.error("Background analysis failed for %s: %s: %s", capture_id, err_name, err_detail)

        info = capture.get_capture(capture_id) or info
        info.analysis_status = "error"
        info.analysis_error = f"{err_name}: {err_detail}"
        capture._captures[capture_id] = info
        capture._save_metadata(info)


@router.post("/{capture_id}/analyze")
async def analyze_capture(capture_id: str, req: AnalysisRequest):
    """Launch AI analysis as a background task.

    Returns immediately with status. The frontend polls GET /analysis
    or GET /{capture_id} (which has analysis_status) to track progress.
    The user can navigate away — analysis continues server-side.
    """
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")

    # Don't start duplicate analyses
    if info.analysis_status == "running":
        return {
            "status": "already_running",
            "capture_id": capture_id,
            "message": "Analysis is already in progress.",
        }

    # Mark as pending and launch background task
    info.analysis_status = "pending"
    capture._captures[capture_id] = info
    capture._save_metadata(info)

    asyncio.create_task(_run_analysis_background(capture_id, req))

    return {
        "status": "started",
        "capture_id": capture_id,
        "message": "Analysis started. Poll GET /captures/{id} or GET /captures/{id}/analysis for results.",
    }


@router.get("/{capture_id}/analysis", response_model=AnalysisResultV2)
async def get_analysis(capture_id: str):
    """Get previous AI analysis results."""
    result = ai_analyzer.get_analysis(capture_id)
    if not result:
        # Check if analysis is in progress
        info = capture.get_capture(capture_id)
        if info and info.analysis_status in ("pending", "running"):
            raise HTTPException(202, "Analysis is still in progress")
        raise HTTPException(404, "No analysis found for this capture")
    return result
