"""Captures router — packet capture CRUD, summary, AI analysis, packs."""

from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

from ..models.analysis_packs import PackConfig, list_packs
from ..models.capture import (
    AnalysisRequest,
    AnalysisResultV2,
    CaptureInfo,
    CaptureSummary,
    StartCaptureRequest,
)
from ..services import ai_analyzer, capture, capture_retention

router = APIRouter(prefix="/api/v1/captures", tags=["captures"])


# ── Pack definitions ─────────────────────────────────────────────────────────

@router.get("/packs", response_model=List[PackConfig])
async def get_packs():
    """List all available analysis packs."""
    return list_packs()


# ── Capture CRUD ─────────────────────────────────────────────────────────────

@router.post("", response_model=CaptureInfo, status_code=201)
async def start_capture(req: StartCaptureRequest):
    """Start a new packet capture. Auto-links to active session."""
    try:
        info = await capture.start_capture(req)
    except ValueError as e:
        raise HTTPException(400, str(e))

    from ..services import session_manager
    from ..models.session import ArtifactType
    await session_manager.auto_add_artifact(
        ArtifactType.CAPTURE,
        name=f"Capture: {info.name}",
        file_path=info.pcap_path,
        tags=["capture", "pcap", info.pack],
        metadata={"capture_id": info.id, "interface": info.interface, "bpf": info.bpf_expression, "pack": info.pack},
    )

    return info


@router.get("", response_model=List[CaptureInfo])
async def list_captures():
    """List all captures."""
    return await capture.list_captures()


@router.get("/status")
async def capture_status():
    """Get capture system status — storage usage, active captures."""
    storage = await capture_retention.get_storage_usage()
    captures = await capture.list_captures()
    active = [c for c in captures if c.status == "running"]

    return {
        "active_captures": len(active),
        "max_concurrent": 2,
        "storage": storage,
    }


@router.get("/{capture_id}", response_model=CaptureInfo)
async def get_capture(capture_id: str):
    """Get capture metadata."""
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")
    return info


@router.post("/{capture_id}/stop", response_model=CaptureInfo)
async def stop_capture(capture_id: str):
    """Stop a running capture."""
    try:
        return await capture.stop_capture(capture_id)
    except ValueError as e:
        raise HTTPException(404, str(e))


@router.delete("/{capture_id}")
async def delete_capture(capture_id: str):
    """Delete a capture and its files."""
    try:
        await capture.delete_capture(capture_id)
        return {"status": "ok", "capture_id": capture_id}
    except ValueError as e:
        raise HTTPException(404, str(e))


@router.get("/{capture_id}/download")
async def download_capture(capture_id: str):
    """Download the pcap file."""
    pcap = capture.get_pcap_path(capture_id)
    if not pcap:
        raise HTTPException(404, "Pcap file not found")
    return FileResponse(
        pcap,
        media_type="application/vnd.tcpdump.pcap",
        filename=f"{capture_id}.pcap",
    )


# ── Summary ──────────────────────────────────────────────────────────────────

@router.get("/{capture_id}/summary")
async def get_summary(capture_id: str):
    """Get the CaptureSummary for a completed capture.

    Returns structured statistics generated by the post-processing pipeline.
    This is the same data used as input to AI analysis.
    """
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")

    summary = capture.get_summary(capture_id)
    if not summary:
        raise HTTPException(404, "Summary not yet available. Capture may still be processing.")

    return summary


# ── AI Analysis ──────────────────────────────────────────────────────────────

@router.post("/{capture_id}/analyze", response_model=AnalysisResultV2)
async def analyze_capture(capture_id: str, req: AnalysisRequest):
    """Run AI analysis on a capture using the v2 evidence-based pipeline."""
    info = capture.get_capture(capture_id)
    if not info:
        raise HTTPException(404, f"Capture '{capture_id}' not found")

    result = await ai_analyzer.analyze_capture(capture_id, req)

    from ..services import session_manager
    from ..models.session import ArtifactType
    await session_manager.auto_add_artifact(
        ArtifactType.ANALYSIS,
        name=f"AI Analysis: {capture_id}",
        data={
            "summary": result.summary,
            "finding_count": len(result.findings),
            "health_badge": result.health_badge.value,
            "provider": result.provider,
        },
        tags=["analysis", "ai", result.provider, info.pack],
        metadata={"capture_id": capture_id},
    )

    return result


@router.get("/{capture_id}/analysis", response_model=AnalysisResultV2)
async def get_analysis(capture_id: str):
    """Get previous AI analysis results."""
    result = ai_analyzer.get_analysis(capture_id)
    if not result:
        raise HTTPException(404, "No analysis found for this capture")
    return result
