"""STB_AUTOMATION — Test flow recording, editing, and replay.

Test flows are editable JSON sequences of ``TestStep`` objects.  They
can be created manually, recorded during navigation, generated by the
NL runner, or extracted from chaos mode.

**Recording**: during ``/navigate`` calls, each step is captured with
pre/post fingerprints and settle timing.

**Replay**: executes steps sequentially with optional assertion checking
(expected screen after each step).  On assertion failure, optionally
collects diagnostics and can use the nav model to recover.
"""

import asyncio
import json
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from ...services import storage
from . import action_executor, diagnostics, fingerprint as fp, nav_model, screen_reader
from .anomaly_detector import get_detector
from .logcat_monitor import get_monitor
from .models import TestFlow, TestFlowRun, TestStep

logger = logging.getLogger("wifry.stb_automation.test_flows")

# In-memory registries
_flows: Dict[str, TestFlow] = {}
_active_run: Optional[TestFlowRun] = None
_run_task: Optional[asyncio.Task] = None
_run_cancel = asyncio.Event()
_loaded = False


def _store_dir() -> Path:
    return storage.ensure_data_path("stb_test_flows")


# ── Persistence ─────────────────────────────────────────────────────


def _load_all() -> None:
    """Load all flows from disk on first access."""
    global _loaded
    if _loaded:
        return
    store = _store_dir()
    for path in store.glob("*.json"):
        try:
            data = json.loads(path.read_text())
            flow = TestFlow(**data)
            _flows[flow.id] = flow
        except (json.JSONDecodeError, Exception) as e:
            logger.warning("[STB_AUTOMATION] Failed to load flow %s: %s", path.name, e)
    _loaded = True
    logger.debug("[STB_AUTOMATION] Loaded %d test flows from disk", len(_flows))


def _save_flow(flow: TestFlow) -> None:
    """Persist a single flow to disk."""
    path = _store_dir() / f"{flow.id}.json"
    path.write_text(json.dumps(flow.model_dump(), indent=2))


def _delete_flow_file(flow_id: str) -> None:
    path = _store_dir() / f"{flow_id}.json"
    if path.exists():
        path.unlink()


# ── CRUD ────────────────────────────────────────────────────────────


def list_flows() -> List[TestFlow]:
    _load_all()
    return list(_flows.values())


def get_flow(flow_id: str) -> Optional[TestFlow]:
    _load_all()
    return _flows.get(flow_id)


def create_flow(
    name: str,
    serial: str,
    description: str = "",
    steps: Optional[List[TestStep]] = None,
    source: str = "manual",
) -> TestFlow:
    """Create a new test flow."""
    _load_all()
    now = datetime.now(timezone.utc).isoformat()
    flow = TestFlow(
        id=uuid.uuid4().hex[:12],
        name=name,
        description=description,
        serial=serial,
        steps=steps or [],
        created_at=now,
        updated_at=now,
        source=source,
    )
    _flows[flow.id] = flow
    _save_flow(flow)
    logger.info("[STB_AUTOMATION] Flow created: %s (%s)", flow.id, name)
    return flow


def update_flow(flow_id: str, updates: dict) -> Optional[TestFlow]:
    """Update a flow's fields.  Returns None if not found."""
    _load_all()
    flow = _flows.get(flow_id)
    if flow is None:
        return None

    if "name" in updates:
        flow.name = updates["name"]
    if "description" in updates:
        flow.description = updates["description"]
    if "steps" in updates:
        flow.steps = [TestStep(**s) if isinstance(s, dict) else s for s in updates["steps"]]
    if "serial" in updates:
        flow.serial = updates["serial"]

    flow.updated_at = datetime.now(timezone.utc).isoformat()
    _save_flow(flow)
    return flow


def delete_flow(flow_id: str) -> bool:
    _load_all()
    if flow_id not in _flows:
        return False
    del _flows[flow_id]
    _delete_flow_file(flow_id)
    logger.info("[STB_AUTOMATION] Flow deleted: %s", flow_id)
    return True


# ── Recording ───────────────────────────────────────────────────────

# Active recording state
_recording_flow_id: Optional[str] = None


def start_recording(name: str, serial: str, description: str = "") -> TestFlow:
    """Start recording navigation steps into a new flow."""
    global _recording_flow_id
    flow = create_flow(name=name, serial=serial, description=description, source="recorded")
    _recording_flow_id = flow.id
    logger.info("[STB_AUTOMATION] Recording started: %s", flow.id)
    return flow


def stop_recording() -> Optional[TestFlow]:
    """Stop recording and return the completed flow."""
    global _recording_flow_id
    if _recording_flow_id is None:
        return None
    flow = get_flow(_recording_flow_id)
    _recording_flow_id = None
    if flow:
        _save_flow(flow)
        logger.info("[STB_AUTOMATION] Recording stopped: %s (%d steps)", flow.id, len(flow.steps))
    return flow


def record_step(
    action: str,
    pre_fingerprint: str,
    post_fingerprint: str,
    settle_ms: float,
    description: str = "",
) -> Optional[TestStep]:
    """Add a step to the active recording.  Called from /navigate."""
    if _recording_flow_id is None:
        return None
    flow = get_flow(_recording_flow_id)
    if flow is None:
        return None

    step = TestStep(
        action=action,
        expected_screen_id=post_fingerprint,
        description=description or f"{action} -> {post_fingerprint[:8]}",
    )
    flow.steps.append(step)
    flow.updated_at = datetime.now(timezone.utc).isoformat()
    _save_flow(flow)
    return step


def is_recording() -> bool:
    return _recording_flow_id is not None


def get_recording_flow_id() -> Optional[str]:
    return _recording_flow_id


# ── Replay ──────────────────────────────────────────────────────────


def get_run_status() -> Optional[TestFlowRun]:
    return _active_run.model_copy() if _active_run else None


async def run_flow(flow_id: str) -> TestFlowRun:
    """Start replaying a test flow as a background task."""
    global _active_run, _run_task

    flow = get_flow(flow_id)
    if flow is None:
        raise ValueError(f"Flow {flow_id} not found")

    if _active_run and _active_run.state == "running":
        raise ValueError("A flow is already running")

    _active_run = TestFlowRun(
        flow_id=flow_id,
        state="running",
        started_at=datetime.now(timezone.utc).isoformat(),
    )
    _run_cancel.clear()
    _run_task = asyncio.create_task(_replay_loop(flow))
    return _active_run


async def stop_flow() -> Optional[TestFlowRun]:
    """Stop the running flow."""
    global _active_run
    if _active_run is None or _active_run.state != "running":
        return _active_run

    _run_cancel.set()
    if _run_task and not _run_task.done():
        try:
            await asyncio.wait_for(_run_task, timeout=5.0)
        except asyncio.TimeoutError:
            _run_task.cancel()

    _active_run.state = "completed"
    _active_run.completed_at = datetime.now(timezone.utc).isoformat()
    return _active_run


async def _replay_loop(flow: TestFlow) -> None:
    """Execute flow steps sequentially."""
    global _active_run
    if _active_run is None:
        return

    monitor = get_monitor()
    detector = get_detector()

    try:
        for i, step in enumerate(flow.steps):
            if _run_cancel.is_set():
                break

            _active_run.current_step = i

            # Handle special actions
            if step.action == "wait":
                await asyncio.sleep(step.wait_ms / 1000.0)
                _active_run.steps_passed += 1
                continue

            # Execute the key press
            result = await action_executor.navigate(
                serial=flow.serial,
                action=step.action,
                settle_timeout_ms=3000,
                monitor=monitor,
            )

            # Extra wait if specified
            if step.wait_ms > 0:
                await asyncio.sleep(step.wait_ms / 1000.0)

            # ── Assertions ──────────────────────────────────────────
            step_failed = False
            post_fp = fp.fingerprint_from_activity(
                result.post_state.package, result.post_state.activity,
            )

            # ADB-based assertions (activity fingerprint)
            if step.expected_screen_id and post_fp != step.expected_screen_id:
                step_failed = True
                logger.warning(
                    "[STB_AUTOMATION] Flow step %d assertion failed: expected fp %s, got %s",
                    i, step.expected_screen_id[:8], post_fp[:8],
                )
            if step.expected_activity and result.post_state.activity != step.expected_activity:
                step_failed = True
                logger.warning(
                    "[STB_AUTOMATION] Flow step %d assertion failed: expected activity %s, got %s",
                    i, step.expected_activity, result.post_state.activity,
                )

            # Vision-based assertions (work on NAF STBs)
            vision = result.post_state.vision
            if step.expected_screen_type and not step_failed:
                if not vision:
                    logger.warning(
                        "[STB_AUTOMATION] Flow step %d: vision assertion skipped (no vision data)",
                        i,
                    )
                elif vision.screen_type != step.expected_screen_type:
                    step_failed = True
                    logger.warning(
                        "[STB_AUTOMATION] Flow step %d vision assertion failed: expected screen_type=%s, got %s",
                        i, step.expected_screen_type, vision.screen_type,
                    )

            if step.expected_focused_label and not step_failed:
                if not vision:
                    logger.warning(
                        "[STB_AUTOMATION] Flow step %d: vision assertion skipped (no vision data)",
                        i,
                    )
                elif vision.focused_label.lower() != step.expected_focused_label.lower():
                    step_failed = True
                    logger.warning(
                        "[STB_AUTOMATION] Flow step %d vision assertion failed: expected focused=%s, got %s",
                        i, step.expected_focused_label, vision.focused_label,
                    )

            if step_failed:
                _active_run.steps_failed += 1
                if step.collect_diagnostics:
                    await diagnostics.collect_diagnostics(
                        serial=flow.serial,
                        reason="flow_assertion_failed",
                        severity="medium",
                    )
                continue

            _active_run.steps_passed += 1

            # Force diagnostic collection at this step
            if step.collect_diagnostics:
                await diagnostics.collect_diagnostics(
                    serial=flow.serial,
                    reason="flow_step_diagnostic",
                    severity="low",
                )

            # Check for anomalies via logcat
            if monitor.is_active:
                events = monitor.get_events(last_n=5)
                anomalies = detector.check_events(events)
                if anomalies:
                    _active_run.anomalies_detected += len(anomalies)
                    for a in anomalies:
                        await diagnostics.collect_diagnostics(
                            serial=flow.serial,
                            reason=a.pattern_name,
                            severity=a.severity,
                            anomaly=a,
                        )

        if not _run_cancel.is_set():
            _active_run.state = "completed"
        else:
            _active_run.state = "completed"

    except Exception as e:
        logger.exception("[STB_AUTOMATION] Flow replay error")
        _active_run.state = "error"
        _active_run.error = str(e)
    finally:
        _active_run.completed_at = datetime.now(timezone.utc).isoformat()
        logger.info(
            "[STB_AUTOMATION] Flow %s finished: %d passed, %d failed, %d anomalies",
            flow.id,
            _active_run.steps_passed,
            _active_run.steps_failed,
            _active_run.anomalies_detected,
        )
